language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database IF NOT EXISTS errorheromodule;' -uroot
  - mysql -u root errorheromodule < spec/Fixture/data/sql.sql
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then composer global require --dev phpstan/phpstan:^0.8; fi
  - composer dump-autoload -o

before_install:
   - if [[ $TRAVIS_PHP_VERSION = 7.2 ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug  && make && make install && echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi

script:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then ~/.composer/vendor/bin/phpstan analyse src/ --level=7; fi
  - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml; fi
  - if [[ $TRAVIS_PHP_VERSION = "nightly" ]]; then bin/kahlan; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then bin/coveralls -v --exclude-no-stmt; fi

notifications:
    email: false
